experiment:
  # env examples:
    # "MiniGrid-FourRooms-v0"
    # "CustomMountainCar-v0"
    # "CartPole-v1"
    # "Pendulum-v1"
  env_import: "CellGroup-v0"
  name: "first_cell"
  description: "PPO Experiment"
  save_path: "./runs"
  num_envs: 1

environment:
  # init_low: 0.0
  # init_high: 0.0
  reward_type: "min"  # min / mean / sum
  termination_type: "first"  # first / half / all

# normalization:
#   enabled: true
#   norm_obs: true
#   norm_reward: true

algorithm:
  name: "PPO"
  
  # Core hyperparameters
  hyperparameters:
    learning_rate: 3.0e-4
    batch_size: 64
    n_epochs: 5
    n_steps: 1024
    gamma: 0.9
    gae_lambda: 0.95
    clip_range: 0.2
    clip_range_vf: null
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 0.3
    use_sde: false
    sde_sample_freq: 4
    target_kl: null

  tuning:
    enabled: true
    num_trials: 10
    search_space:
      learning_rate: [1e-5, 3e-3]
      gamma: [0.9, 0.999]
      gae_lambda: [0.8, 0.98]
      clip_range: [0.1, 0.3]
      ent_coef: [0.0, 0.1]

training:
  timesteps: 50000   # used for train and resume
  
  # Evaluation during training
  eval_freq: 1000
  n_eval_episodes: 5
  eval_deterministic: true
  
  # Checkpointing
  save_freq: 5000
  save_best_model: true

# Testing/evaluation settings
evaluation:
  episodes: 3
  model_type: "final"
  deterministic: true
  render_mode: "rgb_array"
  save_trajectories: false

# Reproducibility
seed: 42
deterministic_pytorch: true