experiment:
  # env examples:
    # "MiniGrid-FourRooms-v0"
    # "CustomMountainCar-v0"
    # "CartPole-v1"
    # "Pendulum-v1"
  env_import: "CellGroup-v0"
  name: "term_150K_tune"
  description: "PPO Experiment"
  save_path: "./runs"
  num_envs: 1

environment:
  init_low:
    tplus_counts: 100      # T+ cells minimum count
    tprod_counts: 100     # TP cells minimum count  
    tneg_counts: 1.0e-9   # T- cells minimum count (near zero)
    
  init_high:
    tplus_counts: 4000    # T+ cells maximum count
    tprod_counts: 4000   # TP cells maximum count
    tneg_counts: 1.0e-6      # T- cells maximum count

  reward_type: "min"  # min / avg / sum
  termination_type: "first"  # first / half / all

# normalization:
  enabled: false
  norm_obs: false
  norm_reward: false

algorithm:
  name: "PPO"
  
  # Core hyperparameters
  hyperparameters:
    learning_rate: 0.001
    batch_size: 512
    n_epochs: 4
    n_steps: 8192
    gamma: 0.999
    gae_lambda: 0.95
    clip_range: 0.2
    clip_range_vf: null
    ent_coef: 0.025
    vf_coef: 0.5
    max_grad_norm: 0.5
    use_sde: false
    sde_sample_freq: -1
    target_kl: null

  tuning:
    enabled: true
    num_trials: 10
    search_space:
      learning_rate: ['linear', 0.001, 0.008]
      gamma: ['log', 0.997, 0.9999]
      gae_lambda: ['linear', 0.88, 0.98]
      clip_range: ['linear', 0.15, 0.25]
      ent_coef: ['linear', 0.0, 0.1]

training:
  timesteps: 150000   # used for train and resume
  
  # Evaluation during training
  eval_freq: 20000
  n_eval_episodes: 5
  eval_deterministic: true
  
  # Checkpointing
  save_freq: 30000
  save_best_model: true

# Testing/evaluation settings
evaluation:
  episodes: 3
  model_type: "best"
  model_path: null
  trial_to_eval: null
  deterministic: true
  render_mode: "rgb_array"
  save_trajectories: false

# Reproducibility
seed: 42
deterministic_pytorch: true